language: c

compiler:
  - clang
  - gcc

sudo: required

services:
  - docker

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "DC/d6QXq6JiGP416PbFvSUcn7ri/9gNsUF27KnWMbVEvqkO/LKdiD6Wx/jJ2g+TQ7hBrpiy4GuG1cBBtjaaeYJ5r998aDCnJbL6uK/x+NkSEWGkyOXq5jwPDvdJ1YSG8Wg2tga5gwnMUapA9EVeaCMAKVrhu6eih/tnk7UFHfQoOe7k3iNDsXKsfT9TRTGWJrJfp3L9D/TTi3cEmGWpeGrzC1+ze0q6j7c6qmUK1aIXLpxgkmk1CkwtmPHiR/xzP8Yf4x9vbv5EUeL0Nux/yqWpVR1EHaTJaKPS5pb/QPzNuS2pxE5Hw+rjCvP3isF7iPESGuxPugGuXJ02sZmuxgRxRXQ7i/0x+umnoPZPOpiZONVcJd9pBHe9ND5o3eGTHQHkeDbRtsYLRTavPQ4tF+U2fpJH62+dVhTWWLMioPWPQSyAGOOlOW9ikGA15whvMc1msuwgptUzEJJzOm6pr2tk7kx3gKAWKcBEM6gwC6nd2QRORbMQ6GZnJ768hmU0W2dog4qD0IfNNemNwY03J9pNuQxcsOYoD8wfXhc3uaO7cPO/jxyiwDdc30U/C90go2usAxyCrLgPyRVBoCswrP7F9TFDY7FRR0y4zEMRbQ0LxmLmkBNkgNeJ5Qva3kurTbebHtyIkOTeYZasLLCNd3kRi/E0L022N65tZNB+cT08="
    # DEPLOY_USER
    - secure: "BAcuVbPb25SUI9Dg1N2AIh1IimPUJRccxx8iA7EjuO2mXhtf2XjRQCTsgITsezP8U65vjfjIqXFOfySNE4yJpGgEW5Z/Vw7KSSB1t3B9tkOBPDIiIgQLktSjGlCNnSGlzl4S4VjdFSLMti6iA2huViPxkeu/lY9hbUsW7TYHJaCxhKcv6n0xgIPy7ZIDzCcnXPR+E6AIW8wI+btuFIJZt8hNPvXyjprdNK6pwugjrIw08xZfR3sxakRF9QuipknCYRS7aZ5VxH7nCpTcKQQj472TpJQ3Ti9qTVvE2yyPws+ZDeZEZ6HKv3BwiaoiRjZQuqAfz9I+3KffbVgXIE4ownYGH/CwIJ+WfXuaCXT6SlesPmBMWgqHBdspfUk5SoA9wPB1TtdAEcWakUEu4M/ZTws0UKrk7vyxoxpWqrmgfE+MNmo4X2VVndrok16GURGHVuNvIqFiXzVJ2GPj3XTFAferCEzdf9LqPriXTUNRIwI3SQkcwqivUB3EM1gtRY5Mrrk/HBk3tBPWnX3YDR2Lb/cNaOrLwZ7lBBiUw3SwZ74vGfbvy4pPJXUOISQsqZRbExwWiphR4IL0NpQ23rnAsBT5D9ksocf4vozSsC63cSXndo7NoIu0awETpRqKnnZfi5Vb9YZKoHxkW26mAbeb/dOjD3cBzkKgtwuyIHfhdQc="
    # DEPLOY_HOST
    - secure: "MDNCRCRDai2dkwwwDHH84abIoBtR9J7Aq8uFBMGw/L0nERCgHoXd/AdjXux4/o/QQqlSJm8eKKMbMBicQNRnFsm3wp9mZdCQnIC5GSWxzcU/tfJkjwQTxdwj0GqN/fcVd7FDjVlhNFrtwKkHQ/IqgDZU6xLY3fQHMT5iO/nvvdIW3sNbL6nd2+X74eAByUoyItLug5oIGlAtNY9fhYYRGBsPnhYxhNOBxHovvPdIBCDpddJ3h+S6YfOHrWPlDIf3q/4RW1Y82QAJa8Wfs9Zc3VwWpR28703iteK74Yvoe21WoZ2UfOMpLRYHAc4sEvW1PYt6y0smfi1hv4gwAufxXfe5YrfRsIuZ2lw/Lpp07mpDBu0wuXtuL0Lc9CLvqWsG018f52r/tkAqphgbFnOBS7lFbXg0Il5KXiBrhWqpavdksoB0i3pdKXUJsQT1Zge8l7kEevoiIRQRYoFpO2JRnNdHQMTacIZpOsb8q2dxiZzUEjQwq3Yg2ERwdVKd09cMsEHdP+GXOj7/7K3FVjU7pQE10BGm7/5qjIELz3gItQm+EkQMq2ESCL5/JntTQlEBoatDXjA8AjJezEiKpfKgNqgb8j/BkTh/z3nQDNjSBw7bap2eUqdWMXzgbSoNDtVw4ApmXUKJZfUbmosgstdYMzDf5GdQZXnKJoQEjy0gRPI="

before_install:
  # Download Coverity certificate
  - if [ "$TRAVIS_BRANCH" = "coverity_scan" ]; then echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-; fi

addons:
  coverity_scan:
    project:
      name: "lirios/qtaccountsservice"
      description: "Qt-style wrapper to Accounts Service"
    notification_email: pierluigi.fiorini@gmail.com
    build_command_prepend: "qbs-setup-toolchains --detect; qbs-setup-qt /usr/bin/qmake-qt5 qt5; qbs config profiles.qt5.baseProfile ${CC}"
    build_command: "qbs build --no-install -d coveralls-build profile:qt5"
    branch_pattern: coverity_scan

arch:
  artifacts:
    - qbs-shared-artifacts.tar.gz
  packages:
    - qbs
    - qt5-tools
    - qt5-declarative
    #- clazy-git
    - dbus
    - xorg-server-xvfb
  script:
    #- export CLAZY_CHECKS="level1"
    - qbs-setup-toolchains --detect
    - qbs-setup-qt /usr/bin/qmake-qt5 qt5
    - qbs config profiles.qt5.baseProfile ${CC}
    - eval `dbus-launch --sh-syntax` && xvfb-run -a -s "-screen 0 800x600x24" qbs build -d build -j $(nproc) --all-products profile:qt5 modules.qbs.installRoot:/ modules.lirideployment.prefix:/usr

script:
  - "curl -s https://raw.githubusercontent.com/lirios/repotools/develop/travis/docker-travis.sh | bash"

deploy:
  - provider: script
    script: .travis/deploy.sh build/default/qtaccountsservice-artifacts.tar.gz
    skip_cleanup: true
    on:
      branch: master
      condition: "$CC = gcc) && ($TRAVIS_PULL_REQUEST = false"
  - provider: script
    script: .travis/deploy.sh build/default/qtaccountsservice-artifacts.tar.gz
    skip_cleanup: true
    on:
      branch: develop
      condition: "$CC = gcc) && ($TRAVIS_PULL_REQUEST = false"

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
