language: c

compiler:
  - clang
  - gcc

sudo: required

services:
  - docker

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "DC/d6QXq6JiGP416PbFvSUcn7ri/9gNsUF27KnWMbVEvqkO/LKdiD6Wx/jJ2g+TQ7hBrpiy4GuG1cBBtjaaeYJ5r998aDCnJbL6uK/x+NkSEWGkyOXq5jwPDvdJ1YSG8Wg2tga5gwnMUapA9EVeaCMAKVrhu6eih/tnk7UFHfQoOe7k3iNDsXKsfT9TRTGWJrJfp3L9D/TTi3cEmGWpeGrzC1+ze0q6j7c6qmUK1aIXLpxgkmk1CkwtmPHiR/xzP8Yf4x9vbv5EUeL0Nux/yqWpVR1EHaTJaKPS5pb/QPzNuS2pxE5Hw+rjCvP3isF7iPESGuxPugGuXJ02sZmuxgRxRXQ7i/0x+umnoPZPOpiZONVcJd9pBHe9ND5o3eGTHQHkeDbRtsYLRTavPQ4tF+U2fpJH62+dVhTWWLMioPWPQSyAGOOlOW9ikGA15whvMc1msuwgptUzEJJzOm6pr2tk7kx3gKAWKcBEM6gwC6nd2QRORbMQ6GZnJ768hmU0W2dog4qD0IfNNemNwY03J9pNuQxcsOYoD8wfXhc3uaO7cPO/jxyiwDdc30U/C90go2usAxyCrLgPyRVBoCswrP7F9TFDY7FRR0y4zEMRbQ0LxmLmkBNkgNeJ5Qva3kurTbebHtyIkOTeYZasLLCNd3kRi/E0L022N65tZNB+cT08="
    # FTP_USER
    - secure: "A4/529yzbT5nRdzDh6Ns2dVOJ3YtIp7e8TaqtsOHs+z++7PwASeWnZ3buCk4dGfdtSZ28NtMDd2hLQE2qQQieXhHmBGl7Uv94qwI/N0IpRpboQvdUIki/pM5jiNtJAt0RyMyLKoEKbGsPX23rpDGuZrH/d36YfxCb6fJ1z6yZ3CHRILC3Q0XILcp84e39MkRdgco9Y/cKiZQpi5PdvVQGd/rCpUCZePrCnNcFuYRfxBzNWz+BMJFOjgeguFdmGNl9GlF5FyXZzwGw0k+KtPd2bnPJzN1t5fyoJjOGi14Zf42mBEcTpDGlEn2PtwHtJI2FMaBRI9+7efPiEILfap1ikYsGsm4cjddtpB0K3RT1Je0aSQ2Q7gTJpRsh0Lc/J9fgGjuilznWnJId6LpO9FuE0J6Y16k/4jbViIxds1ZEL4QjWbNQRdzu5Wv+ldWAYXLvTXVD/g/RcgdVAMA4Uq6ksD/9iVA2gDOfE3WOAuPvRkhnFZmeGnZaC5uF3znWfhj0BU4FtZblWtI8Br8j7GRG3JnyNS3ZXl1zfFmKCiTE4Pj5mnmCIWvoHfmqSg1TCa+5dMJ//LSFxw7tzRIZdtPklzqTQGC6mfa+fSYe2HZKsVwdXz8QDNeiqbdGlOvStSqm/qhPQchBbzBfPqTnQ548+GkmFX/RWB7lGr9PDXDJww="
    # FTP_PASSWORD
    - secure: "ZJJBj1waxb3Z0lKzDQEXHV/l6n4MIgeod73wWc1zOv0Mdhh+Vb3vhmt3ePioD0dAJ6esFbk6Bhl1Pc53rLwqPy5T8RVQQJdY9LtMYfBTvtdG0zh/abp9I1vF2Vdxve87IgwlHHQp5Kdb+YcARUxc6cZc7jO/LxTzJMQEQtZHQkTJ+h0aIm4kY7JFu8UGaFXNKv9O2IQO4r1BCRMSZMi1a3l8x6V9lV3hWvNwxZ+7MukldynanEgOzAJFnCAQcLuBVfQHzpon7sHgeRJPAJrDx9OjaUy4iXUQRmMzIMAGEcTlMTYOPCIGzda0fZZOejpGrj3hblFMVjai/ibf/d53WvzlluHRMMJ2tCCm05iX5Yrp+jreC00K4QHsEQ9yMrN5cUKDihlKbpdcWtQUka/otQ+Cj81AXUaz/z0/y9B0tp69pBnhAG7VOLJXVLoWxB6nvMTNqrCv0N3GyzBOqCyD+wBf3+DhsN77/ZAqpnHMPHUUbKC/L4rDkW8O5Pj04vLnHNI6MZF5YdMk88W0AHFwho7Y2Y2HdLu8Xb+gwOtCmtWfZo+AFJ3IpMzdIK2Yft2rU0gvQ20fs8AYi1NR3gm3WhV+ZfxqRH0i82Tv+eyg6Ns05cV0WE73mwiqVnnnSnmrX7b6ZhYxUXql7iJGG/t4zRZmHnz/wyW7s8pYEOKA2gQ="
    # FTP_URL
    - secure: "WaHqVaAOSvZdt4NV55FmKzFApl0KGB/Cq5Si52SLstzu4656jiH809SY5mc9Va5X0HylsBTkZuI0noJiL5kqn1hF9hpJ3/65VbqjsqrbYVd/Foet9l0iFP18kZgrT4nDfYwOwCyIVhHIM6mkmIK5YqsNDq6IWmM7onlIGigg3IDcstmS1+PI33TatY4ZS+CmYtVsGEa7UrG19JAMo5joIzKdszqHovJWfWXAiRCr1RDdrT0M0TZkla6PjxTR4gkHoqtwc62YbPQ7zVRdubaM2UfOYvp5TxO+4wS+bcD85+UjQhFNCwZLZIW1VHU2XaZMyM11O1uE2t8JojsFZ59Z1DgU64SPOM4qSa2K2LOZH4qun9byoOClBe4GuquRlJbViPJuDA/ZzVmBkcAjcD/1qcXLsADh+8PaJ9zXoXFUbf+4c2180lRqbqO8aVps3NuukfqbyfkYYyj3yz29dwlQ6Xf3jdkHoIfWFLbRdgmzxaoS8ySerYgy5gIMzzG6ZMNOTFjPlU5BgcYgHAwEcqauPAEFGfxtAbkrxAM1u2QttxhUNCQtimjZAGmTgUIJIl6rnHIZ3kjmCRJTP6lFP0koY7zFwoeMx0v02xhP18xm9jweLM+5OCWrRCWGC1I2itYhnaUVEtZEiO8HUyrXVhY/Zrh3eIpKTVDY8Prh/fC+wyA="

before_install:
  # Download Coverity certificate
  - if [ "$TRAVIS_BRANCH" = "coverity_scan" ]; then echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-; fi

addons:
  coverity_scan:
    project:
      name: "lirios/qtaccountsservice"
      description: "Qt-style wrapper to Accounts Service"
    notification_email: pierluigi.fiorini@gmail.com
    build_command_prepend: "qbs-setup-toolchains --detect; qbs-setup-qt /usr/bin/qmake-qt5 qt5; qbs config profiles.qt5.baseProfile ${CC}"
    build_command: "qbs build --no-install -d coveralls-build profile:qt5"
    branch_pattern: coverity_scan

arch:
  artifacts:
    - qbs-shared-artifacts.tar.gz
  packages:
    - qbs
    - qt5-tools
    - qt5-declarative
    #- clazy-git
    - dbus
    - xorg-server-xvfb
  script:
    #- export CLAZY_CHECKS="level1"
    - qbs-setup-toolchains --detect
    - qbs-setup-qt /usr/bin/qmake-qt5 qt5
    - qbs config profiles.qt5.baseProfile ${CC}
    - eval `dbus-launch --sh-syntax` && xvfb-run -a -s "-screen 0 800x600x24" qbs build -d build -j $(nproc) --all-products profile:qt5 qbs.installRoot:/ qbs.installPrefix:usr

script:
  - "curl -s https://raw.githubusercontent.com/lirios/repotools/develop/travis/docker-travis.sh | bash"

deploy:
  - provider: script
    script: curl --ftp-create-dirs -T build/default/qtaccountsservice-artifacts.tar.gz -u $FTP_USER:$FTP_PASSWORD $FTP_URL/artifacts/master/qtaccountsservice-artifacts.tar.gz
    skip_cleanup: true
    on:
      branch: master
      condition: "$CC = gcc"
  - provider: script
    script: curl --ftp-create-dirs -T build/default/qtaccountsservice-artifacts.tar.gz -u $FTP_USER:$FTP_PASSWORD $FTP_URL/artifacts/develop/qtaccountsservice-artifacts.tar.gz
    skip_cleanup: true
    on:
      branch: develop
      condition: "$CC = gcc"

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
